// Code generated by protoc-gen-go. DO NOT EDIT.
// source: formula.proto

package formula

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Formula struct {
	OpString             string   `protobuf:"bytes,1,opt,name=op_string,json=opString,proto3" json:"op_string,omitempty"`
	Values               []int32  `protobuf:"varint,2,rep,packed,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Formula) Reset()         { *m = Formula{} }
func (m *Formula) String() string { return proto.CompactTextString(m) }
func (*Formula) ProtoMessage()    {}
func (*Formula) Descriptor() ([]byte, []int) {
	return fileDescriptor_7cb3ec12ab48c3fd, []int{0}
}

func (m *Formula) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Formula.Unmarshal(m, b)
}
func (m *Formula) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Formula.Marshal(b, m, deterministic)
}
func (m *Formula) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Formula.Merge(m, src)
}
func (m *Formula) XXX_Size() int {
	return xxx_messageInfo_Formula.Size(m)
}
func (m *Formula) XXX_DiscardUnknown() {
	xxx_messageInfo_Formula.DiscardUnknown(m)
}

var xxx_messageInfo_Formula proto.InternalMessageInfo

func (m *Formula) GetOpString() string {
	if m != nil {
		return m.OpString
	}
	return ""
}

func (m *Formula) GetValues() []int32 {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterType((*Formula)(nil), "formula.Formula")
}

func init() { proto.RegisterFile("formula.proto", fileDescriptor_7cb3ec12ab48c3fd) }

var fileDescriptor_7cb3ec12ab48c3fd = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xcb, 0x2f, 0xca,
	0x2d, 0xcd, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xec, 0xb8,
	0xd8, 0xdd, 0x20, 0x4c, 0x21, 0x69, 0x2e, 0xce, 0xfc, 0x82, 0xf8, 0xe2, 0x92, 0xa2, 0xcc, 0xbc,
	0x74, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x8e, 0xfc, 0x82, 0x60, 0x30, 0x5f, 0x48, 0x8c,
	0x8b, 0xad, 0x2c, 0x31, 0xa7, 0x34, 0xb5, 0x58, 0x82, 0x49, 0x81, 0x59, 0x83, 0x35, 0x08, 0xca,
	0x4b, 0x62, 0x03, 0x9b, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x00, 0x21, 0x5f, 0xe0, 0x60,
	0x00, 0x00, 0x00,
}
