// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nest_formula.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NestFormula struct {
	// Types that are valid to be assigned to Elements:
	//	*NestFormula_Mono
	//	*NestFormula_Poly
	Elements             isNestFormula_Elements `protobuf_oneof:"elements"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *NestFormula) Reset()         { *m = NestFormula{} }
func (m *NestFormula) String() string { return proto.CompactTextString(m) }
func (*NestFormula) ProtoMessage()    {}
func (*NestFormula) Descriptor() ([]byte, []int) {
	return fileDescriptor_897a04f0fec97625, []int{0}
}

func (m *NestFormula) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NestFormula.Unmarshal(m, b)
}
func (m *NestFormula) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NestFormula.Marshal(b, m, deterministic)
}
func (m *NestFormula) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NestFormula.Merge(m, src)
}
func (m *NestFormula) XXX_Size() int {
	return xxx_messageInfo_NestFormula.Size(m)
}
func (m *NestFormula) XXX_DiscardUnknown() {
	xxx_messageInfo_NestFormula.DiscardUnknown(m)
}

var xxx_messageInfo_NestFormula proto.InternalMessageInfo

type isNestFormula_Elements interface {
	isNestFormula_Elements()
}

type NestFormula_Mono struct {
	Mono int32 `protobuf:"varint,1,opt,name=mono,proto3,oneof"`
}

type NestFormula_Poly struct {
	Poly *PolyFormula `protobuf:"bytes,2,opt,name=poly,proto3,oneof"`
}

func (*NestFormula_Mono) isNestFormula_Elements() {}

func (*NestFormula_Poly) isNestFormula_Elements() {}

func (m *NestFormula) GetElements() isNestFormula_Elements {
	if m != nil {
		return m.Elements
	}
	return nil
}

func (m *NestFormula) GetMono() int32 {
	if x, ok := m.GetElements().(*NestFormula_Mono); ok {
		return x.Mono
	}
	return 0
}

func (m *NestFormula) GetPoly() *PolyFormula {
	if x, ok := m.GetElements().(*NestFormula_Poly); ok {
		return x.Poly
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*NestFormula) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*NestFormula_Mono)(nil),
		(*NestFormula_Poly)(nil),
	}
}

type PolyFormula struct {
	OpString             string         `protobuf:"bytes,1,opt,name=op_string,json=opString,proto3" json:"op_string,omitempty"`
	NestFormulas         []*NestFormula `protobuf:"bytes,2,rep,name=nest_formulas,json=nestFormulas,proto3" json:"nest_formulas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PolyFormula) Reset()         { *m = PolyFormula{} }
func (m *PolyFormula) String() string { return proto.CompactTextString(m) }
func (*PolyFormula) ProtoMessage()    {}
func (*PolyFormula) Descriptor() ([]byte, []int) {
	return fileDescriptor_897a04f0fec97625, []int{1}
}

func (m *PolyFormula) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PolyFormula.Unmarshal(m, b)
}
func (m *PolyFormula) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PolyFormula.Marshal(b, m, deterministic)
}
func (m *PolyFormula) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PolyFormula.Merge(m, src)
}
func (m *PolyFormula) XXX_Size() int {
	return xxx_messageInfo_PolyFormula.Size(m)
}
func (m *PolyFormula) XXX_DiscardUnknown() {
	xxx_messageInfo_PolyFormula.DiscardUnknown(m)
}

var xxx_messageInfo_PolyFormula proto.InternalMessageInfo

func (m *PolyFormula) GetOpString() string {
	if m != nil {
		return m.OpString
	}
	return ""
}

func (m *PolyFormula) GetNestFormulas() []*NestFormula {
	if m != nil {
		return m.NestFormulas
	}
	return nil
}

func init() {
	proto.RegisterType((*NestFormula)(nil), "api.NestFormula")
	proto.RegisterType((*PolyFormula)(nil), "api.PolyFormula")
}

func init() { proto.RegisterFile("nest_formula.proto", fileDescriptor_897a04f0fec97625) }

var fileDescriptor_897a04f0fec97625 = []byte{
	// 177 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xca, 0x4b, 0x2d, 0x2e,
	0x89, 0x4f, 0xcb, 0x2f, 0xca, 0x2d, 0xcd, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x4e, 0x2c, 0xc8, 0x54, 0x0a, 0xe7, 0xe2, 0xf6, 0x4b, 0x2d, 0x2e, 0x71, 0x83, 0xc8, 0x08, 0x89,
	0x70, 0xb1, 0xe4, 0xe6, 0xe7, 0xe5, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x7a, 0x30, 0x04, 0x81,
	0x79, 0x42, 0x6a, 0x5c, 0x2c, 0x05, 0xf9, 0x39, 0x95, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46,
	0x02, 0x7a, 0x89, 0x05, 0x99, 0x7a, 0x01, 0xf9, 0x39, 0x95, 0x50, 0x5d, 0x20, 0x75, 0x20, 0x79,
	0x27, 0x2e, 0x2e, 0x8e, 0xd4, 0x9c, 0xd4, 0xdc, 0xd4, 0xbc, 0x92, 0x62, 0xa5, 0x44, 0x2e, 0x6e,
	0x24, 0x25, 0x42, 0xd2, 0x5c, 0x9c, 0xf9, 0x05, 0xf1, 0xc5, 0x25, 0x45, 0x99, 0x79, 0xe9, 0x60,
	0xd3, 0x39, 0x83, 0x38, 0xf2, 0x0b, 0x82, 0xc1, 0x7c, 0x21, 0x53, 0x2e, 0x5e, 0x64, 0xf7, 0x15,
	0x4b, 0x30, 0x29, 0x30, 0xc3, 0x2d, 0x42, 0x72, 0x5e, 0x10, 0x4f, 0x1e, 0x82, 0x53, 0x9c, 0xc4,
	0x06, 0xf6, 0x87, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x05, 0xa3, 0x81, 0xc2, 0xdd, 0x00, 0x00,
	0x00,
}
